// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Inbox struct {
	ID        int64
	UserID    string
	Payload   []byte
	CreatedAt pgtype.Timestamp
}

type RendezvousBundle struct {
	RoomID string
	Role   string
	Bundle []byte
}

type RendezvousPubkey struct {
	RoomID string
	Role   string
	Pubkey []byte
}

type RendezvousRoom struct {
	ID        string
	ExpiresAt pgtype.Timestamp
}
