// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"
)

const insertRoom = `-- name: InsertRoom :exec
insert into rendezvous_rooms
    (id, created_by, expires_at)
values($1,$2,$3)
`

type InsertRoomParams struct {
	ID        string
	CreatedBy string
	ExpiresAt time.Time
}

func (q *Queries) InsertRoom(ctx context.Context, arg InsertRoomParams) error {
	_, err := q.db.ExecContext(ctx, insertRoom, arg.ID, arg.CreatedBy, arg.ExpiresAt)
	return err
}
